### ISSUE TITLE
Compiler error with const

### ISSUE THREAD

**Issue by pr0g** [google/cpp-from-the-sky-down#3]
Hello there,

After watching the excellent CppCon talk by John Bandela (https://youtu.be/PSxo85L2lC0) I've been experimenting with the `polymorphic` library but have run into a strange compile error I've been struggling to work out. Here's the snippet I have...

```c++
#include "polymorphic.hpp"

#include <iostream>
#include <string>
#include <vector>
#include <memory>

struct Box {
    void draw() const {
        std::cout << "box" << "\n";
    }
};

struct Circle {
    void draw() const {
        std::cout << "circle" << "\n";
    }
};

struct Triangle {
    void draw() const {
        std::cout << "triangle" << "\n";
    }
};

struct draw {};
using draw_signature = void(draw) const;

void drawing(polymorphic::ref<draw_signature> drawable) {
    drawable.call<draw>();
}

template<typename T>
void poly_extend(draw, const T& t) {
    t.draw();
}

using shape = polymorphic::object<draw_signature>;

int main(int argc, char** argv) {
    Circle c;
    Box b;
    Triangle t;

    drawing(b);
    drawing(c);
    drawing(t);

    shape s1 {c};
    drawing(s1); // does not compile

    return 0;
}
```
If you do a find-replace and remove all the `const`s it totally compiles and runs fine - if someone could tell me what I'm doing wrong I'd be very grateful!

Thanks!

Tom

**Comment by jbandela** [comment]
Thanks for your kind words about the talk and for trying out the library.

One of the helper classes, ptr_holder was missing the constructor overload
for shared_ptr_holder which is used to hold objects that only have const
operations.

I just pushed a commit to the git repo to fix that. If you pull down the
latest repo and build it should work.

I created a Godbolt example of your problem, and it works after the latest
change.

https://gcc.godbolt.org/z/51efVl

Thanks again for letting me know about this. Let me know if any
other issues arise.

- John

**Comment by pr0g** [comment]
Hi John,

Not at all, I really enjoyed it! And the library is a brilliant idea, I'd love if functionality like this was available out of the box with C++ (I believe something like this is now possible in languages such as Go and Rust). 

Ah I see! Thank you for explaining this issue, I'm glad I hadn't missed something too obvious in my code.

I'll grab the updated change this evening and give it a whirl and let you know if everything is working as expected.

No problem! Absolutely, if I run into anything else I'll let you know 🙂

Thanks for the quick response and fix!

All the best,


Tom

**Comment by pr0g** [comment]
Just to confirm the latest change did fix my issue. I added an additional test using a vector and `for` loop too which worked a treat 🙂

My final example looks like this:

```c++
#include "polymorphic.hpp"

#include <iostream>
#include <vector>

struct Square {
    void draw() const {
        std::cout << "square\n";
    }
};

struct Circle {
    void draw() const {
        std::cout << "circle\n";
    }
};

struct Triangle {
    void draw() const {
        std::cout << "triangle\n";
    }
};

struct draw_proc {};
using draw_signature = void(draw_proc) const;

void drawing(polymorphic::ref<draw_signature> drawable) {
    drawable.call<draw_proc>();
}

template<typename T>
void poly_extend(draw_proc, const T& t) {
    t.draw();
}

using Shape = polymorphic::object<draw_signature>;

int main(int argc, char** argv) {
    Circle circle;
    Square square;
    Triangle triangle;

    drawing(square);
    drawing(circle);
    drawing(triangle);

    Shape shape {circle};
    drawing(shape);

    std::vector<Shape> shapes;
    shapes.push_back(Circle{});
    shapes.push_back(Square{});
    shapes.push_back(Triangle{});

    shapes.push_back(triangle);
    shapes.push_back(square);
    shapes.push_back(circle);

    for (const auto& s : shapes) {
        drawing(s);
    }

    return 0;
}
```

I have one quick question about the library. One thing I'm having trouble wrapping my head around is `poly_extend`. From the calling code I invoke `drawing` which then uses the `polymorphic::ref` type to invoke `call` (using the `draw_proc` struct to dispatch to) but I'm not sure how `poly_extend` is then called. Also if this were a library could the `poly_extend` function be hidden in a .cpp or would that always need to be in a header?

Thanks again!


Tom

**Comment by jbandela** [comment]
In regards to poly_extend, it gets called through the trampoline function
in the vtable.

poly_extend needs to be visible (declaration only is fine) at the point
where you create a poly::object or poly::ref from a concrete type. Once you
are working with poly::object, or poly::ref, poly_extend does not need to
be visible.

Hope this helps.

If you have a specific scenario that you would like me to analyze, please
let me know.

- John

**Comment by pr0g** [comment]
Hi John,

Thank you for the explanation, it's a lot clearer now.

I found I did need my `poly_extend` implementation to be in the header for my use case but as there'll usually be very little code there it should be fine.

I've actually just uploaded a really simple example using the library here - https://github.com/pr0g/cpp-sky-down-example. Please let me know if I am missing any sort of accreditation or if there's an issue with the license or how I've called it out.

I found the example to be a helpful way to demo how the library works and the separation of concerns. I'd love to try and use it in a bigger project if I can find the time! 😝

Thanks again for all your help!

Cheers,


Tom
